### ISSUE TITLE
No UD from 09/01/2016 to 11/01/2016

### ISSUE THREAD

**Issue by galuel** [ucoin-io/sakia#340] opened 2016-01-11 09:05 UTC
Date : 11/01/2016

No UD since the last one that was : 08/01/2016 : 8,264 dDU (what is dDU !??)

I checked ID is still a member : 

ID : galuelien
pubkey : Hwe81ooDH23JGDifZ6ytBGrjhGWGnkcGSZnXFWaV9a9a

**Comment by Insoleet** [comment] 2016-01-11 09:08
dDU is deciDU ;)

It's a bug with 0.13 version I think ( sakia is only display the result of the url dividends/pubkey , what do you think @c-geek  ?)

**Comment by galuel** [comment] 2016-01-11 09:21
"dDU is deciDU ;)"

This is not a standard way at all. I suggest to put in the same line than the dates at the top like it is now : 

- Date of begining
- Date of end
- Name of the money used
- Referential (Units, UD, RZ, QZ...)
- Number of digits after comma
- 10<sup>-x</sup> where "x" is so the choice of the user to see deci, centi, milli etc. By default "x" = 0. [In english](http://www.anglaisfacile.com/forum/lire.php?msg=28547&titre=Les+puissances%3F).

The balance should be placed at the bottom of the transactions, not at the top like now (we usually make operations from top to down to obtain a result.

**Comment by c-geek** [comment] 2016-01-11 09:25
I don't know, uCoin data is good:

* http://metab.ucoin.io/blockchain/with/ud
* http://metab.ucoin.io/blockchain/block/47403 (09/01/2015)
* http://metab.ucoin.io/blockchain/block/47439 (10/01/2015)

Isn't it a problem of Integer size of Sakia side? I cleared my cache and still Sakia is stuck at 99% of transaction retrieval.

**Comment by c-geek** [comment] 2016-01-11 09:26
Also noted:

```
Task exception was never retrieved
future: <Task finished coro=<_refresh() done, defined at /home/travis/build/ucoin-io/sakia/src/sakia/core/txhistory.py:234> exception=UnboundLocalError("local variable 'json_data' referenced before assignment",)>
Traceback (most recent call last):
  File "/home/travis/.pyenv/versions/3.4.3/lib/python3.4/asyncio/tasks.py", line 238, in _step
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/txhistory.py", line 272, in _refresh
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/txhistory.py", line 205, in _parse_block
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/txhistory.py", line 131, in _parse_transaction
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/registry/identities.py", line 113, in future_find
  File "/home/travis/build/ucoin-io/sakia/src/sakia/core/net/api/bma/access.py", line 284, in simple_request
UnboundLocalError: local variable 'json_data' referenced before assignment
```

**Comment by Insoleet** [comment] 2016-01-11 09:29
Yes same problem as https://github.com/ucoin-io/sakia/issues/337

Basically, some fields changed in 0.13 ( https://github.com/ucoin-io/ucoin/issues/301 ) and now Sakia is rejecting data from the nodes. This error happens when the cache is cleared AND nodes are sending wrong data, but it's a sakia bug (coupled with the fact that I need to update ucoinpy to the new version field, string or int...)

**Comment by c-geek** [comment] 2016-01-11 09:35
It just `version` field or others too?

**Comment by Insoleet** [comment] 2016-01-11 09:38
All errors I see is about `version` field in the memberships URL.

**Comment by Insoleet** [comment] 2016-01-12 04:19
Duplicate of https://github.com/ucoin-io/sakia/issues/339

**Closed by Insoleet** 2016-01-12 04:19 UTC
Labels: bug
